[tool.black]
line_length = 119

[tool.poetry]
name = "cbwebreader"
version = "0.2"
description = "CBR/Z Web Reader"
authors = ["ajurna <ajurna@gmail.com>"]
license = "Creative Commons Attribution-ShareAlike 4.0 International License"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.1.2"
gunicorn = "^20.0.4"
django-recaptcha2 = "^1.4.1"
dj-database-url = "^0.5.0"
python-dotenv = "^0.15.0"
loguru = "^0.5.3"
django-silk = "^4.1.0"
mysqlclient = "^2.0.1"
psycopg2 = "^2.8.6"
rarfile = "^4.0"
coverage = "^5.5"
django-extensions = "^3.1.3"
Pillow = "^8.2.0"
django-imagekit = "^4.0.2"
PyMuPDF = "^1.18.12"
django-bootstrap4 = "^3.0.0"

[tool.poetry.dev-dependencies]
mypy = "^0.812"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
