[tool.black]
line_length = 119
exclude = 'snapshots'

[tool.isort]
line_length = 119
known_first_party = "comic,comic_auth,cbreader"
known_third_party = "snowpenguin"
default_section = "THIRDPARTY"
skip_glob = "**/migrations/*,**/snapshots/*"
# For compatibility with black:
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"