[tool.black]
line_length = 119

[tool.poetry]
name = "cbwebreader"
version = "1.1.1"
description = "CBR/Z Web Reader"
authors = ["ajurna <ajurna@gmail.com>"]
license = "Creative Commons Attribution-ShareAlike 4.0 International License"

[tool.poetry.dependencies]
python = "^3.10"
Django = "4.1.1"
gunicorn = "^20.0.4"
dj-database-url = "^1.0.0"
python-dotenv = "^0.21.0"
loguru = "^0.6.0"
django-silk = "^5.0.0"
mysqlclient = "^2.0.1"
psycopg2 = "^2.8.6"
rarfile = "^4.0"
django-extensions = "^3.2.1"
Pillow = "^9.3.0"
django-imagekit = "^4.0.2"
PyMuPDF = "~1.20.2"
django-bootstrap4 = "^22.1"
django-csp = "^3.7"
django-boost = "^2.1"
django-sri = "^0.5.0"
django-permissions-policy = "^4.9.0"
djangorestframework = "^3.13.1"
django-filter = "^22.1"
django-cors-headers = "^3.13.0"
djangorestframework-simplejwt = "^5.2.0"
django-webpack-loader = "^1.6.0"
drf-yasg = "^1.20.0"
drf-extensions = "^0.7.1"
flake8 = "^5.0.4"
flake8-annotations = "^2.9.1"

[tool.poetry.dev-dependencies]
mypy = "^0.971"
Werkzeug = "^2.2"
pyOpenSSL = "^22.0.0"
ipython = "^8.4.0"
coverage = "^6.2"
pre-commit = "^2.20.0"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.0"
pylint-django = "^2.5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
