[tool.black]
line_length = 119

[tool.poetry]
name = "cbwebreader"
version = "0.3.5"
description = "CBR/Z Web Reader"
authors = ["ajurna <ajurna@gmail.com>"]
license = "Creative Commons Attribution-ShareAlike 4.0 International License"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.11"
gunicorn = "^20.0.4"
django-recaptcha2 = "^1.4.1"
dj-database-url = "^0.5.0"
python-dotenv = "^0.19.2"
loguru = "^0.5.3"
django-silk = "^4.1.0"
mysqlclient = "^2.0.1"
psycopg2 = "^2.8.6"
rarfile = "^4.0"
coverage = "^6.2"
django-extensions = "^3.1.3"
Pillow = "^9.0.1"
django-imagekit = "^4.0.2"
PyMuPDF = "~1.18"
django-bootstrap4 = "^21.1"
django-csp = "^3.7"
django-boost = "^1.7.2"
django-sri = "^0.3.0"
django-node-assets = "^0.9.9"

[tool.poetry.dev-dependencies]
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
