name: Build and push image

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
#      - name: Install Docker
#        run: curl -fsSL https://get.docker.com | sh
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-python@v4

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.5.1"
      - uses: actions/checkout@v3
      - name: Set FOO
        run: echo "FOO=${{ poetry -V }}" >> $GITHUB_ENV
      - name: Test
        run: echo $FOO
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: false
#          tags: ajurna/cbwebreader:latest
