name: Build and push image

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /repo
    steps:
      - name: Checkout repo
        run: git pull

      - name: Deploy
        run: |
          docker build . --no-cache -t ajurna/cbwebreader
