name: Build and push image

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        run: git pull

      - name: Build
        run: |
          docker build . --no-cache -t ajurna/cbwebreader
