name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.1.15"]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Generate Requirements
      run: poetry export --without-hashes -f requirements.txt --output requirements.txt
    - name: Set env
      run: echo "CB_VERSION=$(poetry version -s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ajurna/cbwebreader:$CB_VERSION
